apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-django
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-django
  template:
    metadata:
      labels:
        app: hello-django
    spec:
      containers:
      - name: django
        image: gcr.io/devopsgcp-470806/hello-django:v1
        ports:
        - containerPort: 8000
        volumeMounts:               
        - name: gcp-key
          mountPath: /secrets
          readOnly: true
        env:                         
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /secrets/gcp-key.json
      volumes:                       
      - name: gcp-key
        secret:
          secretName: gcp-key
